// src/content/index.ts

import { CLAUDE_CANVAS } from '../seo'

export const hero = {
  name: 'Santiago Gómez de la Torre Romero',
  title: { es: 'Full-Stack Engineer | AI/LLM en producción | Creador de NudaUI', en: 'Full-Stack Engineer | AI/LLM in production | Creator of NudaUI' },
  subtitle: { es: 'Full-stack engineer que lleva la IA a producción, no a demos. Creador de NudaUI y de una búsqueda semántica en vivo sobre su catálogo.', en: 'Full-stack engineer who takes AI to production, not to demos. Creator of NudaUI and of a live semantic search over its catalog.' },
}

export const about = {
  description: { es: `
Hay personas que llegan a la tecnología por casualidad. Yo no.
A mí siempre me atrapó entender cómo funciona todo por dentro: cómo se despliega un servicio, por qué un sistema falla, qué hace que una interfaz fluya o se rompa. Con el tiempo, esa curiosidad dejó de ser un impulso y se convirtió en mi forma de trabajar, que consiste en entender para construir y construir para mejorar.

Mi trayectoria combina administración de sistemas, desarrollo web y arquitectura en la nube, siempre con una mentalidad autodidacta y orientada a buenas prácticas. A lo largo de los años he trabajado con React, Angular, Node.js, Firebase y Google Cloud, diseñando soluciones que no solo cumplen, sino que se mantienen y evolucionan.

Mi formación se fortaleció en los programas FUNIBER y PROFER, experiencias que me dieron estructura técnica y visión de equipo. Hoy desarrollo software en Evenbytes, creando aplicaciones que deben ser eficientes, escalables y estables porque se usan en entornos reales.

Ahora construyo IA que llega a producto, no a demos. Diseño sistemas que se pueden medir. Uso pipelines de RAG con embeddings y retrieval por coseno, evaluación con golden sets propios y modelos de lenguaje integrados en el producto real. La búsqueda semántica de NudaUI responde en lenguaje natural sobre más de 1.000 componentes, y con evals propias subí la precisión del primer resultado del 67% al 80%. También mantengo en producción un asistente conversacional B2B construido sobre la API de Claude. Todo esto sin frameworks mágicos, entendiendo cada pieza del pipeline.

En 2026 di el paso de dejar de construir solo para otros y cofundé SkyQuetz Consulting con tres socios más, una consultora de software a medida para negocios de habla hispana, en remoto y sin intermediarios. Llevo la ingeniería, y de ahí han salido dos productos propios: Synentria, un motor de auditoría SEO y GEO cuyos hallazgos son deterministas y no los decide ningún modelo, y Packatrack, un SaaS de conciliación de liquidaciones. Cofundar cambia el trabajo más de lo que parece, porque ya no basta con que el código esté bien y hay que decidir el alcance, hablar con el cliente y responder del resultado.

También participo activamente en la comunidad. Competí en Hack2Progress y organizo eventos con GDG Santander, donde conecto con desarrolladores, estudiantes y profesionales que comparten mi pasión por construir.

Uno de mis proyectos más representativos es EliteEstate Manager, una solución inmobiliaria creada desde cero para resolver necesidades reales. Más que código, fue arquitectura, diseño, producto y visión end-to-end.

Y cuando no construyo para clientes, construyo para la comunidad. Soy el creador y mantenedor de NudaUI, una librería open-source con más de 1.000 componentes UI copy-paste en 81 categorías que funcionan en cualquier framework, y de sgomez-cli, una herramienta publicada en npm para arrancar proyectos full-stack en un solo comando. En 2026 se sumó Claude Canvas, un plugin de Claude Code que le da al modelo una pantalla propia, un panel de terminal interactivo donde eliges, apruebas o rellenas, y tu respuesta le vuelve como un valor exacto. Partí del proof of concept de David Siegel y lo llevé a algo que aguanta el uso diario, con una sola capa de IPC donde había dos incompatibles, cuatro primitivas reutilizables, composición, más de 600 tests y CI en Linux, macOS y Windows donde no había ni un test.
`, en: `
Some people come to technology by chance. I didn't.
I have always been hooked on understanding how everything works on the inside: how a service gets deployed, why a system fails, what makes an interface flow or break. Over time, that curiosity stopped being an impulse and became my way of working, which is to understand in order to build and to build in order to improve.

My career combines systems administration, web development and cloud architecture, always with a self-taught mindset focused on good practices. Over the years I have worked with React, Angular, Node.js, Firebase and Google Cloud, designing solutions that don't just do the job but are maintained and evolve.

My training was strengthened in the FUNIBER and PROFER programs, experiences that gave me technical structure and a team perspective. Today I develop software at Evenbytes, building applications that have to be efficient, scalable and stable because they are used in real environments.

Now I build AI that reaches the product, not demos. I design systems that can be measured. I use RAG pipelines with embeddings and cosine retrieval, evaluation with my own golden sets, and language models integrated into the real product. NudaUI's semantic search answers in natural language over more than 1,000 components, and with my own evals I raised first-result precision from 67% to 80%. I also keep in production a B2B conversational assistant built on the Claude API. All of this without magic frameworks, understanding every piece of the pipeline.

In 2026 I took the step of no longer building only for others and co-founded SkyQuetz Consulting with three more partners, a custom software consultancy for Spanish-speaking businesses, remote and with no intermediaries. I lead the engineering, and two products of our own have come out of it: Synentria, an SEO and GEO audit engine whose findings are deterministic and not decided by any model, and Packatrack, a SaaS for settlement reconciliation. Co-founding changes the work more than it seems, because it is no longer enough for the code to be good and you have to decide the scope, talk to the client and answer for the result.

I also take an active part in the community. I competed in Hack2Progress and I organize events with GDG Santander, where I connect with developers, students and professionals who share my passion for building.

One of my most representative projects is EliteEstate Manager, a real estate solution built from scratch to solve real needs. More than code, it was architecture, design, product and end-to-end vision.

And when I'm not building for clients, I build for the community. I am the creator and maintainer of NudaUI, an open-source library with more than 1,000 copy-paste UI components in 81 categories that work in any framework, and of sgomez-cli, a tool published on npm to start full-stack projects in a single command. In 2026 Claude Canvas joined them, a Claude Code plugin that gives the model a screen of its own, an interactive terminal pane where you choose, approve or fill in, and your answer comes back to it as an exact value. I started from David Siegel's proof of concept and took it to something that holds up under daily use, with a single IPC layer where there had been two incompatible ones, four reusable primitives, composition, more than 600 tests, and CI on Linux, macOS and Windows where there had not been a single test.
` },
  timeline: [
    { year: '2021', title: { es: 'Inicios en el Desarrollo', en: 'Getting Started in Development' }, desc: { es: 'Comienzo en FUNIBER como parte del equipo de redacción técnica. Primeros proyectos personales con React y PWAs.', en: 'Started at FUNIBER as part of the technical writing team. First personal projects with React and PWAs.' } },
    { year: '2022', title: { es: 'Sysadmin & QA', en: 'Sysadmin & QA' }, desc: { es: 'Promoción a Sysadmin en FUNIBER. Gestión de infraestructura tecnológica y aseguramiento de calidad.', en: 'Promoted to Sysadmin at FUNIBER. Managing technology infrastructure and quality assurance.' } },
    { year: '2023', title: { es: 'Soporte IT Universitario', en: 'University IT Support' }, desc: { es: 'Técnico de Soporte IT en Universidad Europea del Atlántico. Portafolio 3D con Next.js y Framer Motion.', en: 'IT Support Technician at Universidad Europea del Atlántico. 3D portfolio with Next.js and Framer Motion.' } },
    { year: '2024', title: { es: 'Comunidad & Eventos', en: 'Community & Events' }, desc: { es: 'Organizador de GDG Santander. Participación en Hack2Progress. Consolidación como desarrollador full-stack.', en: 'Organizer at GDG Santander. Took part in Hack2Progress. Consolidated as a full-stack developer.' } },
    { year: '2025', title: { es: 'Desarrollador Profesional', en: 'Professional Developer' }, desc: { es: 'EliteEstate Manager para Irma Romero. Developer en Evenbytes con Angular, Node.js y GCP. Múltiples recomendaciones profesionales.', en: 'EliteEstate Manager for Irma Romero. Developer at Evenbytes with Angular, Node.js and GCP. Multiple professional recommendations.' } },
    { year: '2026', title: { es: 'Cofundador de SkyQuetz', en: 'SkyQuetz Co-founder' }, desc: { es: 'Cofundé SkyQuetz Consulting con tres socios. Llevo la ingeniería y los productos propios (Synentria, motor de auditoría SEO y GEO, y Packatrack). En paralelo publico Claude Canvas, un plugin open source que le da a Claude Code una pantalla propia. También cofundé Forgia con otro socio y llevo su parte técnica.', en: 'Co-founded SkyQuetz Consulting with three partners. I lead the engineering and the in-house products (Synentria, an SEO and GEO audit engine, and Packatrack). In parallel I publish Claude Canvas, an open-source plugin that gives Claude Code a screen of its own. I also co-founded Forgia with one other partner and lead its technical side.' } },
  ],
}

/**
 * SkyQuetz Consulting — la consultora que cofundé.
 *
 * Los datos de aquí son los MISMOS que declara skyquetz.com en su propio
 * JSON-LD (fecha de fundación, número de socios, eslogan, productos). No se
 * escriben "a ojo": si las dos webs dicen cosas distintas de la misma
 * empresa, un motor no las resuelve como una sola entidad y el enlace entre
 * los dos dominios deja de valer lo que tiene que valer.
 */
export const skyquetz = {
  name: 'SkyQuetz Consulting',
  role: { es: 'Cofundador', en: 'Co-founder' },
  slogan: 'Estándar internacional, trato cercano.', // frase de marca: solo existe en español
  url: 'https://skyquetz.com',
  cta: 'skyquetz.com',
  logo: '/brand/skyquetz-logo.webp',
  logoAlt: { es: 'Logotipo de SkyQuetz Consulting', en: 'SkyQuetz Consulting logo' },
  desc: { es: 'Consultora tecnológica que fundé en 2026 con tres socios más. Construimos software a medida para negocios de habla hispana, desde sistemas y plataformas hasta automatizaciones, tiendas y páginas web. Todo en remoto y sin intermediarios, porque cada proyecto lo lidera en persona el ingeniero que lo escribe.', en: 'A technology consultancy I founded in 2026 with three more partners. We build custom software for Spanish-speaking businesses, from systems and platforms to automations, online stores and websites. All of it remote and with no intermediaries, because every project is led in person by the engineer who writes it.' },
  myPart: { es: 'Mi parte es la ingeniería, que incluye la arquitectura, el código y los productos propios que salen de la casa.', en: 'My part is the engineering, which covers the architecture, the code and the in-house products that come out of the company.' },
  stats: [
    { value: '2026', label: { es: 'fundada', en: 'founded' } },
    { value: '4', label: { es: 'socios', en: 'partners' } },
    { value: '100%', label: { es: 'remoto', en: 'remote' } },
  ],
  products: [
    {
      name: 'Synentria',
      tagline: { es: 'Motor de auditoría SEO y GEO', en: 'SEO and GEO audit engine' },
      desc: { es: 'Le pasas la URL de un sitio y devuelve hallazgos priorizados más parches aplicables. Ningún hallazgo lo decide un modelo de lenguaje, porque todos salen de comprobaciones deterministas, y un modelo solo redacta prosa alrededor de un hallazgo que ya existe. Escribí el motor.', en: `You give it a site's URL and it returns prioritized findings plus applicable patches. No finding is decided by a language model, because they all come from deterministic checks, and a model only writes prose around a finding that already exists. I wrote the engine.` },
      stack: ['TypeScript', 'Nuxt', 'Node', 'Evals'],
      url: 'https://synentria.skyquetz.com',
      cta: 'synentria.skyquetz.com',
    },
    {
      name: 'Packatrack',
      tagline: { es: 'Conciliación de liquidaciones B2B', en: 'B2B settlement reconciliation' },
      desc: { es: 'SaaS para operadores de última milla que calcula lo que una operación debía facturar a partir de sus rutas, tarifas e incidencias, compara el resultado con la liquidación que recibió del carrier y documenta cada diferencia con su dato de origen.', en: 'SaaS for last-mile operators that calculates what an operation should have billed from its routes, rates and incidents, compares the result with the settlement received from the carrier and documents every difference with its source data.' },
      stack: ['React', 'Docker', 'Jenkins', 'SonarQube'],
      url: 'https://packatrack.skyquetz.com',
      cta: 'packatrack.skyquetz.com',
    },
  ],
}

export const certifications = [
  { title: "Software Engineer Intern", institution: "HackerRank", date: { es: "Septiembre 2025", en: "September 2025" }, img: "/models/assets/certifications/hackerrank.png", url: "https://drive.google.com/file/d/1IXV7yxijNfycqqqMvovNXFZMOV6fjJkK/view?usp=sharing" },
  { title: "McKinsey.org Forward Program", institution: "McKinsey.org", date: { es: "Julio 2025", en: "July 2025" }, img: "/models/assets/certifications/mckinsey.png", url: "https://drive.google.com/file/d/1hbWX1oyBi8zUXPsgUtvgZ8ueekno31pz/view?usp=sharing" },
  { title: "Angular (basic)", institution: "HackerRank", date: { es: "Junio 2025", en: "June 2025" }, img: "/models/assets/certifications/hackerrank.png", url: "https://drive.google.com/file/d/1DqpO9M0GigJT43VKkulbZuwKg6-HT1Ab/view?usp=sharing" },
  { title: "Software Engineer", institution: "HackerRank", date: { es: "Mayo 2025", en: "May 2025" }, img: "/models/assets/certifications/hackerrank.png", url: "https://drive.google.com/file/d/10MHq7lyYelaamoLLJhwOc_BVsdtK3qQ4/view?usp=sharing" },
  { title: "Frontend Developer (React)", institution: "HackerRank", date: { es: "Mayo 2025", en: "May 2025" }, img: "/models/assets/certifications/hackerrank.png", url: "https://drive.google.com/file/d/1CQH076Ss81QmlBZJ9wSyvOx7HTk-gK-y/view?usp=sharing" },
  { title: "SCHNEIDER ELECTRIC Hackathon 2025 - IT Challenge", institution: "NUWE", date: { es: "Abril 2025", en: "April 2025" }, img: "/models/assets/certifications/nuwe.png", url: "https://drive.google.com/file/d/15L_2k12CsYcxovvqJzgoC56p05Ypz-xC/view?usp=sharing" },
  { title: "Master en JavaScript 2025: Aprender JS, Angular, Node, Astro", institution: "Udemy", date: { es: "Marzo 2025", en: "March 2025" }, img: "/models/assets/certifications/udemy.png", url: "https://drive.google.com/file/d/10FqgAblTBp76CKhc31ZnV0LW-D3kkXuB/view?usp=sharing" },
  { title: "The Web Developer Bootcamp 2025", institution: "Udemy", date: { es: "Marzo 2025", en: "March 2025" }, img: "/models/assets/certifications/udemy.png", url: "https://drive.google.com/file/d/1XQsTwo88A7isHT2pSBEuoNTFjYhzY81j/view?usp=sharing" },
  { title: "Azure DevOps: Flujos de CI/CD", institution: "Platzi", date: { es: "Marzo 2025", en: "March 2025" }, img: "/models/assets/certifications/platzi.png", url: "https://drive.google.com/file/d/1pcAssPwA5b3rep77kcW8azReUbFYXzC9/view?usp=sharing" },
  { title: "Certificado de Participación Hack2Progress", institution: "CIC Consulting Informático", date: { es: "Marzo 2025", en: "March 2025" }, img: "/models/assets/certifications/cic.png", url: "https://drive.google.com/file/d/14IbZJ8hqiM2lUPb1YBftxyfgWTB6jK-d/view?usp=sharing" },
  { title: "Machine Learning y Data Science", institution: "Udemy", date: { es: "Marzo 2025", en: "March 2025" }, img: "/models/assets/certifications/udemy.png", url: "https://drive.google.com/file/d/1isr8dB1w1pUFD4T704k2xI0R4rUrV_N4/view?usp=sharing" },
  { title: "Cómo incluir la sostenibilidad en tu estrategia de cloud computing", institution: "LinkedIn", date: { es: "Marzo 2025", en: "March 2025" }, img: "/models/assets/certifications/linkedin.png", url: "https://drive.google.com/file/d/1JYMq9yOPD0qRMB4gB_Gy9SbZ3qo3ZVh8/view?usp=sharing" },
  { title: "Resolución de problemas con el pensamiento crítico", institution: "LinkedIn", date: { es: "Marzo 2025", en: "March 2025" }, img: "/models/assets/certifications/linkedin.png", url: "https://drive.google.com/file/d/1G_RkQD-O23AEpnj_JKOEjJ2wYeFFFMXN/view?usp=sharing" },
  { title: "Prompt Engineering", institution: "LinkedIn", date: { es: "Marzo 2025", en: "March 2025" }, img: "/models/assets/certifications/linkedin.png", url: "https://drive.google.com/file/d/1SegpNdQ74TAK6TrkJDaHNcjINyoXjXY1/view?usp=sharing" },
  { title: "Master en React", institution: "Udemy", date: { es: "Diciembre 2024", en: "December 2024" }, img: "/models/assets/certifications/udemy.png", url: "https://drive.google.com/file/d/1woMqIXOjTDeTFTQXy2kdL33zgIMe4WYJ/view?usp=sharing" },
  { title: "Legacy Front End", institution: "freecodecamp", date: { es: "Noviembre 2024", en: "November 2024" }, img: "/models/assets/certifications/freecodecamp.png", url: "https://drive.google.com/file/d/1ohmcttf7Ca81d_JhHg9sdReB1zHwaWqO/view?usp=sharing" },
  { title: "JavaScript Algorithms and Data Structures (Beta)", institution: "freecodecamp", date: { es: "Noviembre 2024", en: "November 2024" }, img: "/models/assets/certifications/freecodecamp.png", url: "https://drive.google.com/file/d/1DGM402G6EroGk3meZJnBRufImBAnMNVn/view?usp=sharing" },
  { title: "Responsive Web Design", institution: "freecodecamp", date: { es: "Noviembre 2024", en: "November 2024" }, img: "/models/assets/certifications/freecodecamp.png", url: "https://drive.google.com/file/d/1YFgrFhli2ruL2XrMhXtfYfsnCuwpDQBe/view?usp=sharing" },
  { title: "Front End Development Libraries", institution: "freecodecamp", date: { es: "Noviembre 2024", en: "November 2024" }, img: "/models/assets/certifications/freecodecamp.png", url: "https://drive.google.com/file/d/1kUM-BD4FoJUl70jTpp-5UVhrCgotXh2n/view?usp=sharing" },
  { title: "Certificado de Participación", institution: "Universidad Europea del Atlantico", date: { es: "Julio 2024", en: "July 2024" }, img: "/models/assets/certifications/uneatlantico.png", url: "https://drive.google.com/file/d/1wfl_0Dlw17CMrVMIq51I7Sgf5UPhd5Kz/view?usp=sharing" },
];

export const projects = [
  { title: 'Claude Canvas', desc: { es: `${CLAUDE_CANVAS.description} Es un fork del proof of concept de David Siegel, ampliado a fondo, con una sola capa de IPC donde había dos incompatibles, primitivas reutilizables, composición, más de 600 tests y CI en tres sistemas operativos donde no había ninguno.`, en: `${CLAUDE_CANVAS.descriptionEn} It is a fork of David Siegel's proof of concept, extended at length, with one IPC layer where there had been two incompatible ones, reusable primitives, composition, more than 600 tests and CI on three operating systems where there had been none.` }, stack: 'TypeScript, Bun, React, Ink, tmux', link: 'https://claude-canvas.sgomez.dev' },
  { title: 'NudaUI Semantic Search (RAG)', desc: { es: 'Búsqueda en lenguaje natural sobre 1.000+ componentes de NudaUI. Pipeline de RAG completo, sin frameworks de RAG. Incluye embeddings con Voyage, retrieval por coseno, evaluación con un golden set propio, servicio en FastAPI y UI en vivo. Subí la precisión del primer resultado del 67% al 80% (hit@1) y reporté hasta la categoría que empeoró.', en: 'Natural-language search over 1,000+ NudaUI components. A complete RAG pipeline with no RAG frameworks. It includes embeddings with Voyage, cosine retrieval, evaluation with my own golden set, a FastAPI service and a live UI. I raised first-result precision from 67% to 80% (hit@1) and reported even the category that got worse.' }, stack: 'RAG, Embeddings, Python, FastAPI, Evals', link: 'https://blog.sgomez.dev/rag-busqueda-semantica-nudaui' },
  { title: 'NudaUI', desc: { es: 'Librería open-source de 1.000+ componentes y animaciones UI copy-paste, framework-agnósticos (HTML + CSS, JS solo cuando hace falta), organizados en 81 categorías. Cero dependencias, cero build. Creador y único mantenedor.', en: 'Open-source library of 1,000+ copy-paste UI components and animations, framework-agnostic (HTML + CSS, JS only when needed), organized in 81 categories. Zero dependencies, zero build. Creator and sole maintainer.' }, stack: 'Next.js, TypeScript, CSS, framework-agnostic', link: 'https://nudaui.dev' },
  { title: 'EliteEstate Manager', desc: { es: 'PWA de gestión inmobiliaria completa con autenticación, propiedades, citas, zonas y panel de administración. Proyecto end-to-end para cliente real.', en: 'Complete real estate management PWA with authentication, properties, appointments, zones and an admin panel. End-to-end project for a real client.' }, stack: 'React, Vite, Firebase, TailwindCSS', link: 'https://elite-estate-manager.vercel.app/' },
  { title: 'GeekLab', desc: { es: 'E-commerce full-stack de productos IT con catálogo avanzado, carrito persistente, foro en tiempo real con WebSockets, API GraphQL y panel admin.', en: 'Full-stack e-commerce of IT products with an advanced catalog, persistent cart, real-time forum with WebSockets, GraphQL API and admin panel.' }, stack: 'Svelte 5, Node.js, Express, MongoDB, GraphQL, Socket.io', link: 'https://github.com/sgomez-dev/GeekLab' },
  { title: 'SyncCart', desc: { es: 'Extensión de Chrome que unifica carritos de compra de múltiples tiendas (Amazon, PcComponentes, MediaMarkt) en una sola interfaz con calculadora de presupuesto.', en: 'Chrome extension that unifies shopping carts from multiple stores (Amazon, PcComponentes, MediaMarkt) in a single interface with a budget calculator.' }, stack: 'Plasmo, React 18, TypeScript, Chrome APIs', link: 'https://github.com/sgomez-dev/SyncCart' },
  { title: 'Sortlab', desc: { es: 'Visualizador interactivo de 15 algoritmos de ordenamiento con animaciones dinámicas y explicaciones estructuradas.', en: 'Interactive visualizer of 15 sorting algorithms with dynamic animations and structured explanations.' }, stack: 'React, TypeScript, Framer Motion', link: 'https://sortlab.sgomez.dev' },
  { title: 'Docs - SGOMEZ', desc: { es: 'Documentación visual de mi stack tecnológico con interfaz temática galáctica.', en: 'Visual documentation of my technology stack with a galaxy-themed interface.' }, stack: 'React, Vite, TailwindCSS, Framer Motion', link: 'https://docs.sgomez.dev' },
  { title: 'CorvexTalk.AI', desc: { es: 'Chat de traducción con inteligencia artificial. Desplegado con Docker y pipeline CI/CD en Jenkins.', en: 'Translation chat powered by artificial intelligence. Deployed with Docker and a CI/CD pipeline in Jenkins.' }, stack: 'Node.js, JavaScript, Docker, Jenkins', link: 'https://corvex-talk-ai.vercel.app' },
  { title: 'sgomez CLI', desc: { es: 'CLI publicada en npm para inicializar proyectos frontend y backend con múltiples frameworks.', en: 'CLI published on npm to initialize frontend and backend projects with multiple frameworks.' }, stack: 'Node.js, npm', link: 'https://www.npmjs.com/package/sgomez-cli' },
  { title: 'Skyzen', desc: { es: 'App de clima en tiempo real con geolocalización y pronóstico extendido.', en: 'Real-time weather app with geolocation and extended forecast.' }, stack: 'React, Vite, TailwindCSS, Framer Motion', link: 'https://skyzen.sgomez.dev' },
  { title: 'Galardón', desc: { es: 'Web app para crear y compartir invitaciones de graduación digitales.', en: 'Web app to create and share digital graduation invitations.' }, stack: 'Vue, TypeScript, CSS', link: 'https://galardon-gamma.vercel.app' },
]

export const education = [
  { title: 'Universidad Europea del Atlántico', desc: { es: '2021 - Actualidad | Grado en ingeniería informática', en: `2021 - Present | Bachelor's degree in Computer Engineering` } },
]

export const experience = [
  { organization: 'Forgia', location: { es: 'Santander, Cantabria, España', en: 'Santander, Cantabria, Spain' }, role: { es: 'Cofundador', en: 'Co-founder' }, desc: { es: 'Cofundé Forgia junto a otro socio, una empresa que desarrolla un sistema de bots de IA que atiende a clientes y cualifica leads por WhatsApp y redes sociales. Su producto, Forgia IA, reúne un bot inbound que responde a las consultas entrantes, un bot outbound para la prospección B2B automatizada y un panel CRM para gestionar los leads en tiempo real. Somos dos socios fundadores y llevo toda la parte técnica, que abarca arquitectura, desarrollo, los bots y el CRM.', en: 'I co-founded Forgia with one other partner, a company that builds an AI bot system that answers customers and qualifies leads over WhatsApp and social media. Its product, Forgia IA, brings together an inbound bot that answers incoming enquiries, an outbound bot for automated B2B prospecting and a CRM panel to manage leads in real time. We are two founding partners and I lead the whole technical side, which covers architecture, development, the bots and the CRM.' }, period: { es: 'Junio 2026 - Actualidad', en: 'June 2026 - Present' } },
  { organization: 'SkyQuetz Consulting', location: { es: 'Remoto (España y Latinoamérica)', en: 'Remote (Spain and Latin America)' }, role: { es: 'Cofundador', en: 'Co-founder' }, desc: { es: 'Cofundé SkyQuetz Consulting con tres socios más para llevar ingeniería de software con estándar internacional a negocios de habla hispana, en remoto y sin intermediarios. Llevo la parte técnica, que abarca arquitectura, desarrollo y decisiones de producto, además de los productos propios de la casa. De ahí salen Synentria, un motor de auditoría SEO y GEO cuyos hallazgos son deterministas y no los decide ningún modelo de lenguaje, y Packatrack, un SaaS de conciliación de liquidaciones para operadores de última milla. Aquí no solo escribo el código, también decido el alcance, hablo con el cliente y respondo del resultado.', en: `I co-founded SkyQuetz Consulting with three more partners to bring software engineering with an international standard to Spanish-speaking businesses, remotely and with no intermediaries. I lead the technical side, which covers architecture, development and product decisions, as well as the company's in-house products. Two products have come out of it: Synentria, an SEO and GEO audit engine whose findings are deterministic and not decided by any language model, and Packatrack, a SaaS for settlement reconciliation for last-mile operators. Here I don't just write the code, I also decide the scope, talk to the client and answer for the result.` }, period: { es: '2026 - Actualidad', en: '2026 - Present' } },
  { organization: 'Evenbytes', location: { es: 'Santa Cruz de Bezana, Cantabria, España', en: 'Santa Cruz de Bezana, Cantabria, Spain' }, role: { es: 'Desarrollador de Software', en: 'Software Developer' }, desc: { es: 'En Evenbytes desarrollo y mantengo aplicaciones web escalables utilizando Angular, Node.js y Google Cloud, construyendo interfaces fluidas, APIs eficientes y sistemas seguros basados en Datastore y autenticación corporativa. Participo activamente en decisiones de arquitectura, revisión de código y definición técnica, asegurando calidad y consistencia en cada entrega. Además de programar, optimizo rendimiento, mejoro procesos y colaboro estrechamente con product managers y arquitectos para transformar requisitos complejos en soluciones claras, funcionales y listas para producción.', en: 'At Evenbytes I develop and maintain scalable web applications using Angular, Node.js and Google Cloud, building smooth interfaces, efficient APIs and secure systems based on Datastore and corporate authentication. I take an active part in architecture decisions, code review and technical definition, ensuring quality and consistency in every delivery. Besides programming, I optimize performance, improve processes and work closely with product managers and architects to turn complex requirements into clear, functional, production-ready solutions.' }, period: { es: 'Junio 2025 - Actualidad', en: 'June 2025 - Present' } },
  { organization: 'Google Developer Group (GDG) Santander', location: { es: 'Santander, Cantabria, España', en: 'Santander, Cantabria, Spain' }, role: { es: 'Organizador', en: 'Organizer' }, desc: { es: 'Como organizador de GDG Santander coordino charlas, talleres y eventos que fortalecen la comunidad tecnológica local, trabajando con ponentes y expertos para ofrecer contenido relevante y práctico. Me encargo de la planificación, logística y difusión de cada actividad, impulsando la participación, el aprendizaje y el crecimiento continuo de la comunidad de desarrolladores y entusiastas de la tecnología.', en: 'As an organizer at GDG Santander I coordinate talks, workshops and events that strengthen the local tech community, working with speakers and experts to deliver relevant, practical content. I handle the planning, logistics and promotion of each activity, driving participation, learning and continuous growth of the community of developers and technology enthusiasts.' }, period: { es: 'Noviembre 2024 - Actualidad', en: 'November 2024 - Present' } },
  { organization: 'Irma Romero Morales', location: { es: 'Santander, Cantabria, España', en: 'Santander, Cantabria, Spain' }, role: { es: 'Desarrollador Full-Stack Freelance', en: 'Freelance Full-Stack Developer' }, desc: { es: 'Desarrollé EliteEstate Manager como freelance para Irma Romero Morales, una PWA completa para la gestión inmobiliaria. Me encargué del diseño, desarrollo y despliegue de la aplicación, creando una interfaz moderna y responsiva con funcionalidades como gestión de propiedades, zonas, agendas y citas. Fue un proyecto end-to-end que reforzó mis habilidades full stack, mi capacidad para trabajar con clientes y mi experiencia construyendo soluciones web reales orientadas a negocio.', en: 'I developed EliteEstate Manager as a freelancer for Irma Romero Morales, a complete PWA for real estate management. I was responsible for the design, development and deployment of the application, creating a modern, responsive interface with features such as management of properties, zones, schedules and appointments. It was an end-to-end project that strengthened my full-stack skills, my ability to work with clients and my experience building real, business-oriented web solutions.' }, period: { es: 'Febrero 2025 - Junio 2025', en: 'February 2025 - June 2025' } },
  { organization: 'Universidad Europea del Atlántico', location: { es: 'Santander, Cantabria, España', en: 'Santander, Cantabria, Spain' }, role: { es: 'Técnico de Soporte IT', en: 'IT Support Technician' }, desc: { es: 'Brindé soporte técnico integral en la Universidad Europea del Atlántico, resolviendo incidencias, asistiendo a usuarios y manteniendo la infraestructura informática del campus. Participé en la mejora de sistemas, documenté procesos y aseguré la continuidad operativa de los servicios tecnológicos. Esta experiencia fortaleció mis habilidades en soporte, trabajo en equipo y gestión de sistemas en un entorno académico de alta demanda.', en: 'I provided comprehensive technical support at the Universidad Europea del Atlántico, resolving incidents, assisting users and maintaining the campus IT infrastructure. I took part in improving systems, documented processes and ensured the operational continuity of technology services. This experience strengthened my skills in support, teamwork and systems management in a high-demand academic environment.' }, period: { es: 'Julio 2023 - Julio 2024', en: 'July 2023 - July 2024' } },
  { organization: 'Fundación Universitaria Iberoamericana (FUNIBER)', location: { es: 'Santander, Cantabria, España', en: 'Santander, Cantabria, Spain' }, role: { es: 'Sysadmin & QA Tester', en: 'Sysadmin & QA Tester' }, desc: { es: 'Desempeñé un rol híbrido de SysAdmin y QA en FUNIBER, gestionando la infraestructura tecnológica y asegurando la disponibilidad de servidores, redes y servicios internos. Realicé mantenimiento preventivo, supervisión de entornos críticos y automatización de procesos, además de coordinar proyectos tecnológicos alineados con los objetivos de la organización. Esta etapa reforzó mis competencias en administración de sistemas, calidad de software y gestión técnica en entornos colaborativos.', en: `I held a hybrid SysAdmin and QA role at FUNIBER, managing the technology infrastructure and ensuring the availability of servers, networks and internal services. I carried out preventive maintenance, monitoring of critical environments and process automation, and also coordinated technology projects aligned with the organization's goals. This stage strengthened my skills in systems administration, software quality and technical management in collaborative environments.` }, period: { es: 'Julio 2022 - Julio 2023', en: 'July 2022 - July 2023' } },
  { organization: 'Fundación Universitaria Iberoamericana (FUNIBER)', location: { es: 'Santander, Cantabria, España', en: 'Santander, Cantabria, Spain' }, role: { es: 'Equipo de Redacción de Correos y Guías Técnicas', en: 'Email and Technical Guides Writing Team' }, desc: { es: 'Formé parte del equipo del Programa de Becas de FUNIBER, creando y revisando comunicaciones académicas e internacionales adaptadas a distintos contextos culturales. Colaboré con el equipo para garantizar coherencia y calidad, actualizando guías y documentos según feedback y buenas prácticas. Esta experiencia reforzó mis habilidades en redacción profesional, atención al detalle y gestión documental en entornos educativos.', en: 'I was part of the FUNIBER Scholarship Program team, creating and reviewing academic and international communications adapted to different cultural contexts. I worked with the team to ensure consistency and quality, updating guides and documents based on feedback and good practices. This experience strengthened my skills in professional writing, attention to detail and document management in educational environments.' }, period: { es: 'Septiembre 2021 - Julio 2022', en: 'September 2021 - July 2022' } },
]

export const recommendations = [
  { name: 'Irma Romero', comment: 'Quiero recomendar ampliamente el trabajo de Santiago, quien desarrolló una aplicación a medida para mi empresa inmobiliaria. La app es muy amigable, fácil de usar y ha sido una herramienta clave para optimizar nuestros procesos internos, especialmente en la gestión de inventarios, citas y tareas administrativas. El servicio fue rápido, profesional y con una atención excelente en cada etapa del proceso.', commentEn: 'I want to highly recommend Santiago\'s work. He developed a custom application for my real estate company. The app is very friendly, easy to use and has been a key tool for optimizing our internal processes, especially inventory, appointment and administrative task management. The service was fast, professional and with excellent attention at every stage of the process.', date: { es: '13 de abril de 2025', en: 'April 13, 2025' }, profileUrl: 'https://www.linkedin.com/in/sgomez-dev/', recommenderUrl: 'https://www.linkedin.com/in/irma-romero-928a9b26/' },
  { name: 'Alejandro Rubio Cao', comment: ['Tuve la oportunidad de trabajar con Santiago en varios proyectos durante nuestra carrera en Ingeniería Informática y dentro del programa de becas de la Universidad Europea del Atlántico, y siempre ha demostrado un gran talento y compromiso. Su capacidad para resolver problemas complejos y su enfoque analítico lo distinguen como un profesional destacado en el campo de la tecnología.', 'No tengo dudas de que su talento y dedicación serán un gran aporte en cualquier desafío que emprenda. Recomiendo a Santiago sin reservas para cualquier oportunidad en el ámbito de la informática.'], commentEn: ['I had the opportunity to work with Santiago on several projects during our Computer Engineering degree and within the scholarship program of the Universidad Europea del Atlántico, and he has always shown great talent and commitment. His ability to solve complex problems and his analytical approach set him apart as an outstanding professional in the field of technology.', 'I have no doubt that his talent and dedication will be a great contribution to any challenge he takes on. I recommend Santiago without reservation for any opportunity in the field of computing.'], date: { es: '10 de abril de 2025', en: 'April 10, 2025' }, profileUrl: 'https://www.linkedin.com/in/sgomez-dev/', recommenderUrl: 'https://www.linkedin.com/in/alejandro-rubio-cao-82b0181b5/' },
  { name: 'Manuel Rondon', comment: 'Tuve la fortuna de trabajar junto a Santiago al inicio de nuestras carreras y desde entonces destacaba su habilidad para adaptarse rapidamente a nuevos conceptos y tecnologías. Mas adelante tambien tuve la oportunidad de participar junto a él en el hackathon Hack2Progress 2025, en el cual demostró cuanto habia crecido su capacidad tecnica y que conservaba esa gran habilidad de adaptarse a cualquier entorno técnico de manera casi inmediata ha sido una pieza vital en nuestra participación y considero que sería una gran adición a cualquier equipo en el que se encuentre', commentEn: 'I was fortunate to work alongside Santiago at the beginning of our careers, and even then his ability to adapt quickly to new concepts and technologies stood out. Later I also had the opportunity to take part with him in the Hack2Progress 2025 hackathon, where he showed how much his technical ability had grown and that he kept that great ability to adapt to any technical environment almost immediately; he was a vital part of our participation and I consider he would be a great addition to any team he is part of', date: { es: '26 de Marzo de 2025', en: 'March 26, 2025' }, profileUrl: 'https://www.linkedin.com/in/sgomez-dev/', recommenderUrl: 'https://www.linkedin.com/in/manuel-rondon-1b2816218/' },
  { name: 'Edgar León Du Solier', comment: 'Tuve el gusto de trabajar junto a Santiago en el área de administración de sistemas, acompañándolo en su proceso de formación. Desde el inicio demostró una gran capacidad para entender rápidamente conceptos técnicos complejos, destacándose especialmente por su velocidad de aprendizaje y la facilidad con la que adoptaba nuevos conocimientos. Su proactividad, acompañada de una notable habilidad para resolver problemas, hacen de él un excelente profesional en crecimiento. Sin duda, recomiendo a Santiago como una gran incorporación para cualquier equipo de trabajo', commentEn: 'I had the pleasure of working alongside Santiago in the systems administration area, supporting him in his training process. From the start he showed a great capacity to quickly understand complex technical concepts, standing out especially for his speed of learning and the ease with which he adopted new knowledge. His proactivity, together with a remarkable ability to solve problems, make him an excellent professional who keeps growing. Without a doubt, I recommend Santiago as a great addition to any work team', date: { es: '24 de Marzo de 2025', en: 'March 24, 2025' }, profileUrl: 'https://www.linkedin.com/in/sgomez-dev/', recommenderUrl: 'https://www.linkedin.com/in/edgarleond/' },
]

export const technologies = [
  { category: { es: 'Frontend', en: 'Frontend' }, skills: [{ name: 'React', years: '3+', icon: '⚛️' }, { name: 'Angular', years: '1+', icon: '🅰️' }, { name: 'Next.js', years: '2+', icon: '▲' }, { name: 'Svelte', years: '1+', icon: '🔥' }, { name: 'TypeScript', years: '2+', icon: '📘' }, { name: 'JavaScript', years: '3+', icon: '📜' }, { name: 'Tailwind CSS', years: '2+', icon: '🎨' }, { name: 'Vite', years: '3+', icon: '⚡' }, { name: 'Framer Motion', years: '1+', icon: '🎬' }] },
  { category: { es: 'Backend', en: 'Backend' }, skills: [{ name: 'Node.js', years: '2+', icon: '🟢' }, { name: 'Express', years: '2+', icon: '🚂' }, { name: 'Python', years: '3+', icon: '🐍' }, { name: 'Firebase', years: '2+', icon: '🔥' }, { name: 'GraphQL', years: '1+', icon: '◈' }] },
  { category: { es: 'DevOps & Cloud', en: 'DevOps & Cloud' }, skills: [{ name: 'Google Cloud', years: '1+', icon: '☁️' }, { name: 'AWS', years: '1+', icon: '☁️' }, { name: 'Docker', years: '2+', icon: '🐳' }, { name: 'Kubernetes', years: '2+', icon: '⎈' }, { name: 'Jenkins', years: '2+', icon: '🔧' }, { name: 'GitHub', years: '5+', icon: '🐙' }] },
  { category: { es: 'Databases & Tools', en: 'Databases & Tools' }, skills: [{ name: 'MongoDB', years: '3+', icon: '🍃' }, { name: 'MySQL', years: '1+', icon: '🐬' }, { name: 'Postman', years: '3+', icon: '📮' }, { name: 'SonarQube', years: '2+', icon: '📊' }, { name: 'n8n', years: '1+', icon: '🔗' }] },
]

export const contactLinks = [
  { label: 'LinkedIn', url: 'https://linkedin.com/in/sgomez-dev', color: 'bg-blue-700' },
  { label: 'GitHub', url: 'https://github.com/sgomez-dev', color: 'bg-gray-800' },
  { label: 'Instagram', url: 'https://instagram.com/santigt1503', color: 'bg-pink-500' },
  { label: 'Facebook', url: 'https://fb.com/santi.gomez.568847', color: 'bg-blue-600' },
]

/**
 * Descripciones de proyecto en tercera persona, para las superficies de
 * agentes (llms.txt, agents.md, la home en markdown). Las de `projects` están
 * escritas en primera persona porque son las de la web; un fichero que habla de
 * él en tercera persona no puede colar un «subí» o un «mi stack» en mitad.
 * Solo los proyectos que usan primera persona tienen variante; el resto sirve
 * su descripción tal cual.
 */
const THIRD_PERSON_DESC: Record<string, { es: string; en: string }> = {
  'NudaUI Semantic Search (RAG)': {
    es: 'Búsqueda en lenguaje natural sobre 1.000+ componentes de NudaUI. Pipeline de RAG completo, sin frameworks de RAG. Incluye embeddings con Voyage, retrieval por coseno, evaluación con un golden set propio, servicio en FastAPI y UI en vivo. Subió la precisión del primer resultado del 67% al 80% (hit@1) y reportó hasta la categoría que empeoró.',
    en: 'Natural-language search over 1,000+ NudaUI components. A complete RAG pipeline with no RAG frameworks. It includes embeddings with Voyage, cosine retrieval, evaluation with its own golden set, a FastAPI service and a live UI. He raised first-result precision from 67% to 80% (hit@1) and reported even the category that got worse.',
  },
  'Docs - SGOMEZ': {
    es: 'Documentación visual de su stack tecnológico con interfaz temática galáctica.',
    en: 'Visual documentation of his technology stack with a galaxy-themed interface.',
  },
}

export function agentProjectDescription(title: string, fallback: string, lang: 'es' | 'en'): string {
  return THIRD_PERSON_DESC[title]?.[lang] ?? fallback
}
